command: [
  "python",
  "app.py",
]
env:
  - name: "DATABRICKS_SQL_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "FILE_METADATA_TABLE"
    value: "procesamiento_archivos.default.iso20022_file_metadata"
  - name: "ABFSS_BASE_URI"
    value: "abfss://archivos@pruebasdatabricksv104.dfs.core.windows.net/inbound/"
  - name: "INPUT_VOLUME_PATH"
    valueFrom: "input-volume"